<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="Shared.props" Condition="Exists('Shared.props')"/>
	<!--<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />-->
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>

		<RootNamespace>$(Vendor).Loader</RootNamespace>
		<!-- значение по умолчанию мин версии-->
		<MinVersion Condition="'$(MinVersion)' == ''">23</MinVersion>

		<!--для GeneratedCompile.cs не удалять-->
		<SolutionNameSafe Condition="'$(SolutionName)'==''">NoSolution</SolutionNameSafe>
		<SolutionNameSafe Condition="'$(SolutionName)'!=''">$(SolutionName)</SolutionNameSafe>
		<CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
		<!--******-->
		<Description>Загрузчик модулей $(SolutionName) под версию nanoCAD ≥ 23</Description>
		<AssemblyTitle>$(SolutionName)$(MSBuildProjectName)</AssemblyTitle>
		<!--metadata-->
		<HostFamily>NC23</HostFamily>
		<HostCode>n</HostCode>
	</PropertyGroup>

	<PropertyGroup>
		<DefineConstants>$(DefineConstants);$(HostFamily)</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="nanoCAD.Platform.NET" Version="23.0.6177.4117" />
	</ItemGroup>
</Project>
