<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>netstandard2.0</TargetFramework>
		<Description>абстракции, интерфейсы</Description>
	</PropertyGroup>
</Project>
