<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>Настройка логирования nLog</Description>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="drzNLog" Version="6.1.0-drz" />
		<!--<PackageReference Include="NLog" Version="6.1.3" />-->
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
</Project>
