<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>Обновляет приложения, чистит  bak файлы</Description>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
	<PropertyGroup>
		<SharedConfigDir>$(MSBuildProjectDirectory)\Shared\7z_32\</SharedConfigDir>
	</PropertyGroup>
	<ItemGroup>
		<Content Include="$(SharedConfigDir)\**\*.*"
				 Exclude="$(SharedConfigDir)\*.ion">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
			<TargetPath>%(Filename)%(Extension)</TargetPath>
		</Content>
	</ItemGroup>
</Project>
