<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>1 чистилка bak и копий</Description>
		<Product>CloneB</Product>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);TEST:A</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="..\src\**\*.cs" Link="\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
		<ProjectReference Include="..\Test.AddOnRuntime\Test.AddOnRuntime.csproj" />
	</ItemGroup>
</Project>
