<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <PlatformTarget>x64</PlatformTarget>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <Description>Проверка SharpSevenZip на архивах 7z с паролем и шифрованными заголовками</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SharpSevenZip" Version="2.0.0" />
  </ItemGroup>

</Project>
