<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>2 чистилка bak и копий</Description>
		<Product>Lib_B</Product>
		<InformationalVersion>Cleaner for 2</InformationalVersion>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);TEST;B</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="..\src\**\*.cs" Link="\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
</Project>
