<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>точка создания контейнера</Description>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
		<ProjectReference Include="..\Cad.Infrastructure\NC.Infrastructure.csproj" />
		<ProjectReference Include="..\LogBootstrap\LogBootstrap.csproj" />
		<ProjectReference Include="..\Infrastructure\Infrastructure.csproj">
			<PrivateAssets>all</PrivateAssets>
		</ProjectReference>
	</ItemGroup>
	<ItemGroup>
		<PackageReference Include="SimpleInjector" Version="5.5.0" >
			<Private>True</Private>
		</PackageReference>
	</ItemGroup>
</Project>
