<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<UseWPF>true</UseWPF>
		<UseWindowsForms>true</UseWindowsForms>
		<Description>SpecSPDS ядро</Description>
		<!--metadata-->
		<HostFamily>NC</HostFamily>
		<HostCode>n</HostCode>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);$(HostFamily)</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="WindowsAPICodePack" Version="7.0.4" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyMetadata Include="HostFamily" Value="$(HostFamily)" />
		<AssemblyMetadata Include="HostCode" Value="$(HostCode)" />
	</ItemGroup>
</Project>