<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>Сервис nanoCAD</Description>
		<UseWPF>true</UseWPF>
		<UseWindowForms>true</UseWindowForms>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);TEST</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<Compile Include="..\Cad.Infrastructure\Services\**\*.cs" Link="\%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>

</Project>
