<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowForms>true</UseWindowForms>
		<Description>Сервис и инфраструктура nanoCAD</Description>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);NC</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="nanoCAD.Platform.NET" Version="23.1.6324.4405" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
</Project>
