<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props" Condition="Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<Description>Сервис и инфраструктура nanoCAD</Description>
		<!--metadata-->
		<HostFamily>NC</HostFamily>
		<HostCode>n</HostCode>
	</PropertyGroup>
	<PropertyGroup>
		<DefineConstants>$(DefineConstants);$(HostFamily)</DefineConstants>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="nanoCAD.Platform.NET" Version="23.1.6324.4405" />
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<AssemblyMetadata Include="HostFamily" Value="$(HostFamily)" />
		<AssemblyMetadata Include="HostCode" Value="$(HostCode)" />
	</ItemGroup>
</Project>
