<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="$(SolutionDir)Directory.Build.props"
	        Condition="'$(SpecSPDSDirectoryBuildImported)' != 'true' And Exists('$(SolutionDir)Directory.Build.props')" />
	<PropertyGroup>
		<TargetFramework>net6.0-windows</TargetFramework>
		<UseWPF>true</UseWPF>
		<UseWindowForms>true</UseWindowForms>
		<Description>Инфраструктура и сервисы</Description>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\Abstractions\Abstractions.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Reference Include="System.Management">
			<HintPath>..\Nuget\System.Management\4.700\System.Management.dll</HintPath>
			<Private>True</Private>
		</Reference>
	</ItemGroup>
</Project>
